### ISSUE TITLE
Versicherungswert von Gemeinschaftsanlagen beim Export ist auf 0 zu setzen

### ISSUE THREAD

**Issue by tnickolaus** [thoherr/brickevent#34]

**Comment by thoherr** [comment]
Spalte Versicherungswert wird bei Anlagen auf 0 gesetzt.
Der erfasste Wert wird bei Gemeinschaftsanlagen in einer neuen Spalte "Versicherungswert Anlage" ausgewiesen.
Das macht z.B. Sinn, wenn die Gemeinschaftsanlage neben den darin enthaltenen MOCs noch weitere Elemente enthält, z.B. Unterbau, Stromversorgung, Beleuchtung etc.
