### ISSUE TITLE
translation missing: de.devise.registrations.user.signed_up_but_unconfirmed

### ISSUE THREAD

**Issue by tnickolaus** [thoherr/brickevent#52]
Fehler nach Registrierung eines neuen Users: 
translation missing: de.devise.registrations.user.signed_up_but_unconfirmed

Die Funktionalität scheint nicht beeinträchtigt zu sein

**Comment by thoherr** [comment]
I18n für neue Devise-Version hatte einige Lücken. Ich habe die beiden locale-Files für Deutsch und Englisch rausgenommen und das Gem devise-i18n installiert, so dass die Lokalisierungen künftig automatisch auf dem aktuellen Stand sind
