### ISSUE TITLE
"Umhängen" von Gemeinschaftsanlagen

### ISSUE THREAD

**Issue by carver0510** [thoherr/brickevent#92]
Wir legen zu Beginn einer Ausstellung (meist vor dem Öffnen der Anmeldung) schon alle Gemeinschaftsanlagen an, damit die Aussteller sich gleich richtig "zuordnen" können. Dies geschieht jedoch unter einer Person. Später würden wir gerne die Gemeinschaftsanlage an den Verantwortlichen "hängen". Dies ist aktuell ein manueller Prozess (neue Dummy Gemeinschaftsanlage unter den Verantwortlichen anlegen, alle MOCs dem neuen Dummy zuordnen, "alte Gemeinschaftsanlage" löschen, Dummy umbenennen).

Es wäre super, wenn man man die Gemeinschaftsanlage (z.B. über einen extra Dialog) einer neuen Person zuordnen könnte.

**Comment by thoherr** [comment]
Erledigt mit https://github.com/thoherr/brickevent/commit/24a5bebe26924a2711ebe723a0a6e772e96ee32a
