### ISSUE TITLE
Import Funktion / Tisch und Positionsnummer

### ISSUE THREAD

**Issue by carver0510** [thoherr/brickevent#93]
Aktuell bearbeiten wir viele Daten in Excel, die wir dann immer wieder manuell zurück spielen müssen.

Es wäre gut, wenn man Daten Exportieren, dann in Excel bearbeiten, und dann wieder zurück importieren könnte.

Aktuell hinterlegen wir in Excel 2 extra Spalten (Tisch- und Positionsnummer). Es wäre super, wenn man diese Daten dann wieder von Excel auf die Eventseite zurückspielen könnte.
MOCs, welcher eine Gemeinschaftsanlage zugeordnet wären, würden dann die Tisch-und Positionsnummer bekommen. (Manchmal schreiben wir in das Feld "Tisch" auch einen Text, wenn dieser eindeutiger als eine Nummer ist.

**Comment by thoherr** [comment]
Ist implementiert mit zwei numerischen Werten "table" und "position". Beispieldatei in test/data
